import { useEffect, useRef, useState } from 'react';
import { ArrowUp, Search, Square, Pencil } from 'lucide-react';
import type { Chat } from '../../shared/contracts';
import { api } from '../services/api';
export function ChatView({ chat, running, liveText, status, send, cancel, editMessage, connected }: { chat?: Chat; running: boolean; liveText: string; status: string; send: (text: string) => void; cancel: () => void; editMessage: (id: string, text: string) => void; connected: boolean }) {
  const [input, setInput] = useState(''); const [editing, setEditing] = useState(''); const [draft, setDraft] = useState(''); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(''); const [results, setResults] = useState<Record<string, any>[]>([]); const [detail, setDetail] = useState<unknown>(); const [searchError, setSearchError] = useState('');
  const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { bottom.current?.scrollIntoView({ block: 'end' }); }, [chat?.messages.length, liveText]);
  async function search() { setSearchError('검색 중…'); try { const result = await api.callPok('search_kb', { query, limit: 30 }); setResults(Array.isArray(result) ? result : []); setDetail(undefined); setSearchError(''); } catch (e) { setSearchError(String(e)); } }
  return <section className="feature chat-view fill"><div className="page-heading"><h1>{chat?.title ?? '새 대화'}</h1><button onClick={() => setSearchOpen(v => !v)}><Search size={14} />지식 검색</button></div>
    {searchOpen && <div className="knowledge-panel"><form className="actions" onSubmit={e => { e.preventDefault(); void search(); }}><input aria-label="게임 지식 검색" value={query} onChange={e => setQuery(e.target.value)} placeholder="아이템·젬·패시브 검색" /><button disabled={!connected || !query.trim()}>검색</button></form><p role="status" className="muted">{connected ? searchError : 'pok 엔진을 먼저 연결하세요.'}</p><div className="knowledge-results">{results.map((r, i) => r.empty ? <p key={i}>{JSON.stringify(r.why)}</p> : <button key={r.id} onClick={() => api.callPok('get_entry', { id: r.id }).then(setDetail).catch(e => setSearchError(String(e)))}>{r.name_ko || r.name_en || r.id}<small>{r.type}</small></button>)}</div>{detail !== undefined && <pre className="knowledge-detail">{JSON.stringify(detail, null, 2)}</pre>}</div>}
    <div className="chat-log scroll">{!chat?.messages.length && <div className="chat-empty"><div className="brand-mark">pk</div><h2>어떤 빌드를 만들어볼까요?</h2><p>게임 지식을 찾고, 장비·스킬·패시브를 함께 다듬으세요.</p><div className="suggestions">{['이 빌드의 약점을 분석해줘', '주력 스킬에 맞는 보조 젬을 찾아줘', '생존력을 유지하면서 DPS를 높여줘'].map(text => <button key={text} onClick={() => setInput(text)}>{text}</button>)}</div></div>}
      {chat?.messages.map(message => <article key={message.id} className={`message ${message.role}`}><header><strong>{message.role === 'user' ? '나' : message.role === 'assistant' ? 'pok 에이전트' : '시스템'}</strong>{message.role === 'user' && !running && <button className="icon-button" aria-label="메시지 편집" onClick={() => { setEditing(message.id); setDraft(message.text); }}><Pencil size={13} /></button>}<time>{new Date(message.at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></header>{editing === message.id ? <div><textarea aria-label="메시지 수정" value={draft} onChange={e => setDraft(e.target.value)} /><p className="muted note">수정한 메시지 이후의 응답은 제거됩니다. 다음 전송에서 새 맥락으로 이어갑니다.</p><div className="actions"><button onClick={() => setEditing('')}>취소</button><button className="primary" onClick={() => { editMessage(message.id, draft); setEditing(''); }}>수정 저장</button></div></div> : <div className={`message-text ${message.status === 'error' ? 'warning' : ''}`}>{message.status === 'streaming' && running ? liveText || status || '응답 준비 중…' : message.text || (message.status === 'streaming' ? '이전 응답이 중단되었습니다.' : '')}</div>}</article>)}<div ref={bottom} /></div>
    <form className="composer" onSubmit={e => { e.preventDefault(); if (!input.trim() || running) return; send(input.trim()); setInput(''); }}><textarea aria-label="에이전트 메시지" placeholder="pok에 질문하거나 빌드 수정을 요청하세요…" value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); if (input.trim() && !running) { send(input.trim()); setInput(''); } } }} /><div className="composer-bottom"><span className="muted">{running ? status || '에이전트 실행 중' : 'Enter 전송 · Shift+Enter 줄바꿈'}</span>{running ? <button type="button" aria-label="응답 중지" onClick={cancel}><Square size={15} /></button> : <button className="primary" aria-label="메시지 보내기" disabled={!input.trim()}><ArrowUp size={17} /></button>}</div></form>
  </section>;
}
