import { useState } from 'react';
import type { BuildEdit, ParsedBuild } from '../../shared/contracts';
export function ConfigView({ parsed, edit }: { parsed: ParsedBuild; edit: (edit: BuildEdit, label: string) => void }) {
  const set = parsed.configs.find(s => s.active) ?? parsed.configs[0];
  const [key, setKey] = useState(''); const [value, setValue] = useState('');
  return <section className="feature scroll"><div className="page-heading"><h1>설정</h1><span className="muted">캐릭터 · 전투 조건</span></div>
    <div className="panel"><header className="panel-heading"><h2>캐릭터</h2></header><div className="panel-body field-grid"><label>레벨<input aria-label="캐릭터 레벨" type="number" min="1" max="100" value={parsed.level} onChange={e => edit({ type: 'character', level: Math.min(100, Math.max(1, Number(e.target.value))), className: parsed.className, ascendancy: parsed.ascendancy }, '캐릭터 레벨 변경')} /></label><label>클래스<input readOnly value={`${parsed.className} · ${parsed.ascendancy}`} /></label></div></div>
    {set && <div className="panel spaced"><header className="panel-heading"><h2>전투 조건</h2><select aria-label="전투 조건 세트" value={set.id} onChange={e => edit({ type: 'active-set', kind: 'config', id: e.target.value }, '전투 조건 변경')}>{parsed.configs.map(c => <option key={c.id} value={c.id}>{c.title || `세트 ${c.id}`}</option>)}</select></header><div className="panel-body"><div className="config-fields">{Object.entries(set.inputs).map(([name, entry]) => <label className={typeof entry === 'boolean' ? 'config-field check' : 'config-field'} key={name}>{typeof entry === 'boolean' ? <><input type="checkbox" checked={entry} onChange={e => edit({ type: 'config', setId: set.id, key: name, value: e.target.checked }, '전투 조건 편집')} /><span>{name}</span></> : <><span>{name}</span>{String(entry).includes('\n') || name === 'customMods' ? <textarea value={String(entry)} onChange={e => edit({ type: 'config', setId: set.id, key: name, value: e.target.value }, '사용자 정의 조건 편집')} /> : <input type={typeof entry === 'number' ? 'number' : 'text'} value={String(entry)} onChange={e => edit({ type: 'config', setId: set.id, key: name, value: typeof entry === 'number' ? Number(e.target.value) : e.target.value }, '전투 조건 편집')} />}</>}</label>)}</div><form className="actions spaced" onSubmit={e => { e.preventDefault(); const v = value === 'true' ? true : value === 'false' ? false : value.trim() && Number.isFinite(Number(value)) ? Number(value) : value; if (key.trim()) edit({ type: 'config', setId: set.id, key: key.trim(), value: v }, '전투 조건 추가'); setKey(''); setValue(''); }}><input required aria-label="새 전투 조건 이름" placeholder="PoB 조건 키" value={key} onChange={e => setKey(e.target.value)} /><input aria-label="새 전투 조건 값" placeholder="값 · true / false / 숫자 / 문자" value={value} onChange={e => setValue(e.target.value)} /><button>조건 추가</button></form><details className="spaced"><summary>원본의 참고값 {set.placeholders.length}개</summary><p className="muted note">Placeholder는 실제 활성 조건과 구분해 보존합니다.</p><pre>{JSON.stringify(set.placeholders, null, 2)}</pre></details></div></div>}
  </section>;
}
