import { useEffect, useState } from 'react';
import type { ConnectionInfo, Settings } from '../../shared/contracts';
import { api } from '../services/api';
export function SettingsView({ settings, save, connect, connection }: { settings: Settings; save: (s: Settings) => void; connect: (s: Settings['pok']) => Promise<void>; connection: ConnectionInfo }) {
  const [draft, setDraft] = useState(settings); const [message, setMessage] = useState('');
  useEffect(() => setDraft(settings), [settings]);
  const browse = async (key: 'root' | 'python' | 'luajit') => { try { const value = await api.selectPath(key === 'root' ? 'directory' : 'executable'); if (value) setDraft(d => ({ ...d, pok: { ...d.pok, [key]: value } })); } catch (e) { setMessage(String(e)); } };
  return <section className="feature settings-view scroll"><div className="page-heading"><h1>pok 설정</h1><span className="muted">앱 · 엔진 · 에이전트</span></div><form onSubmit={e => { e.preventDefault(); save(draft); setMessage('설정을 저장했습니다.'); }}>
    <div className="settings-section"><h2>화면</h2><div className="field-grid"><label>테마<select value={draft.theme} onChange={e => setDraft({ ...draft, theme: e.target.value as Settings['theme'] })}><option value="system">시스템</option><option value="dark">어둡게</option><option value="light">밝게</option></select></label><label>정보 밀도<select value={draft.density} onChange={e => setDraft({ ...draft, density: e.target.value as Settings['density'] })}><option value="compact">촘촘하게</option><option value="comfortable">여유롭게</option></select></label></div></div>
    <div className="settings-section"><h2>pok 엔진</h2><label>실행 방식<select value={draft.pok.mode} onChange={e => setDraft({ ...draft, pok: { ...draft.pok, mode: e.target.value as 'bundled' | 'checkout' } })}><option value="bundled">앱에 포함된 런타임</option><option value="checkout">개발용 체크아웃 연결</option></select></label>{draft.pok.mode === 'checkout' && <>{(['root', 'python', 'luajit'] as const).map((key, i) => <label key={key}>{['pok 프로젝트 폴더', 'Python 실행 파일', 'LuaJIT 실행 파일 (선택)'][i]}<div className="path-field"><input value={draft.pok[key]} onChange={e => setDraft({ ...draft, pok: { ...draft.pok, [key]: e.target.value } })} /><button type="button" onClick={() => void browse(key)}>찾기</button></div></label>)}</>}<div className="actions"><button type="button" onClick={() => { save(draft); void connect(draft.pok); }}>연결 확인</button><span className={connection.connected ? 'success' : 'muted'}>{connection.connected ? `연결됨 · ${connection.tools?.length ?? 0}개 도구` : connection.error || '연결 전'}</span></div></div>
    <div className="settings-section"><h2>AI 에이전트</h2><div className="field-grid"><label>제공자<select value={draft.agent.provider} onChange={e => setDraft({ ...draft, agent: { ...draft.agent, provider: e.target.value as 'codex' | 'claude', executable: e.target.value } })}><option value="codex">Codex</option><option value="claude" disabled>Claude · 연결 준비 중</option></select></label><label>모델<input value={draft.agent.model} onChange={e => setDraft({ ...draft, agent: { ...draft.agent, model: e.target.value } })} placeholder="에이전트 기본 모델 사용" /></label></div><label>에이전트 실행 파일<input value={draft.agent.executable} onChange={e => setDraft({ ...draft, agent: { ...draft.agent, executable: e.target.value } })} placeholder="codex 또는 실행 파일 경로" /></label><p className="muted note">설치된 CLI의 로그인 세션을 사용합니다. 대화는 이 앱의 사용자 데이터 폴더에 보관됩니다.</p></div>
    <div className="settings-section"><h2>거래소</h2><label>기본 리그<input value={draft.trade.league} onChange={e => setDraft({ ...draft, trade: { league: e.target.value } })} placeholder="리그 이름" /></label><p className="muted note">거래소 검색은 pok 에이전트 도구를 통해 요청합니다. 인증 세션 연결은 별도 지원 예정입니다.</p></div>
    <div className="actions"><button className="primary">설정 저장</button><button type="button" onClick={() => api.openDataFolder().catch(e => setMessage(String(e)))}>사용자 데이터 폴더 열기</button><span role="status">{message}</span></div></form></section>;
}
