import { useEffect, useState } from 'react';
import type { ConnectionInfo, Settings } from '../../shared/contracts';
import { api } from '../services/api';
import type { DataBundleInfo } from '../../shared/game-data';
export function SettingsView({ settings, save, connect, connection }: { settings: Settings; save: (s: Settings) => void; connect: (s: Settings['pok']) => Promise<void>; connection: ConnectionInfo }) {
  const [bundle,setBundle]=useState<DataBundleInfo>();
  useEffect(()=>{let active=true;void api.getDataBundleInfo().then(value=>{if(active)setBundle(value);}).catch(error=>{if(active)setBundle({status:'corrupt',error:String(error)});});return()=>{active=false;};},[connection]);
  const [draft, setDraft] = useState(settings); const [message, setMessage] = useState('');
  useEffect(() => setDraft(settings), [settings]);
  const browse = async (key: 'root' | 'python' | 'luajit') => { try { const value = await api.selectPath(key === 'root' ? 'directory' : 'executable'); if (value) setDraft(d => ({ ...d, pok: { ...d.pok, [key]: value } })); } catch (e) { setMessage(String(e)); } };
  return <section className="feature settings-view scroll"><div className="page-heading"><h1>pok 설정</h1><span className="muted">앱 · 엔진 · 에이전트</span></div><form onSubmit={e => { e.preventDefault(); save(draft); setMessage('설정을 저장했습니다.'); }}>
    <div className="settings-section"><h2>화면</h2><div className="field-grid"><label>테마<select value={draft.theme} onChange={e => setDraft({ ...draft, theme: e.target.value as Settings['theme'] })}><option value="system">시스템</option><option value="dark">어둡게</option><option value="light">밝게</option></select></label><label>정보 밀도<select value={draft.density} onChange={e => setDraft({ ...draft, density: e.target.value as Settings['density'] })}><option value="compact">촘촘하게</option><option value="comfortable">여유롭게</option></select></label></div></div>
    <div className="settings-section"><h2>게임 데이터</h2>{bundle?.status==='ready'&&bundle.identity?<><p>{bundle.runtimeMode==='checkout'?'개발 체크아웃 · ':''}POK {bundle.identity.pok.version} · 패치 {bundle.identity.kb.patch || '미지정'} · PoB {bundle.identity.pob.commit.slice(0,7)}</p><p className="muted note">{bundle.runtimeMode==='checkout'?'준비한 고정 데이터와 일치하는 소스 POK에 연결합니다. 이 묶음은 배포할 수 없습니다.':'이 앱에 포함된 고정 버전으로 편집하고 계산합니다.'}</p><details><summary>버전 출처</summary><dl><dt>배포 묶음</dt><dd>{bundle.bundleId}</dd><dt>PoB 커밋</dt><dd>{bundle.identity.pob.commit}</dd><dt>POK 커밋</dt><dd>{bundle.identity.pok.sourceCommit}</dd><dt>지원 트리</dt><dd>{bundle.supportedTreeVersions?.join(', ')}</dd></dl></details></>:<p className="warning">{bundle?.error||'게임 데이터 확인 중…'}</p>}</div>
    <div className="settings-section"><h2>pok 엔진</h2>
      <p className="muted note">{connection.managed ? '앱에 포함된 POK 엔진을 시작할 때 자동으로 실행하고 연결합니다.' : '앱을 시작하면 아래 설정으로 POK 엔진을 자동으로 실행하고 연결합니다.'}</p>
      {!connection.managed && <>
        <label>실행 방식<select disabled={connection.connecting} value={draft.pok.mode} onChange={e => setDraft({ ...draft, pok: { ...draft.pok, mode: e.target.value as 'bundled' | 'checkout' } })}><option value="bundled">앱에 포함된 런타임</option><option value="checkout">개발용 체크아웃 연결</option></select></label>
        {draft.pok.mode === 'checkout' && <>{(['root', 'python', 'luajit'] as const).map((key, i) => <label key={key}>{['pok 프로젝트 폴더', 'Python 실행 파일', 'LuaJIT 실행 파일 (선택)'][i]}<div className="path-field"><input disabled={connection.connecting} value={draft.pok[key]} onChange={e => setDraft({ ...draft, pok: { ...draft.pok, [key]: e.target.value } })} /><button type="button" disabled={connection.connecting} onClick={() => void browse(key)}>찾기</button></div></label>)}</>}
      </>}
      <div className="actions">{(!connection.managed || !connection.connected) && <button type="button" disabled={connection.connecting} onClick={() => { save(draft); void connect(draft.pok); }}>{connection.connecting ? '자동 연결 중…' : connection.connected ? '재연결' : '다시 연결'}</button>}<span className={connection.connected ? 'success' : 'muted'}>{connection.connecting ? '엔진을 시작하고 버전을 확인하는 중입니다.' : connection.connected ? `연결됨 · ${connection.tools?.length ?? 0}개 도구` : connection.error || '자동 연결 대기'}</span></div>
    </div>
    <div className="settings-section"><h2>AI 에이전트</h2><div className="field-grid"><label>제공자<select value={draft.agent.provider} onChange={e => setDraft({ ...draft, agent: { ...draft.agent, provider: e.target.value as 'codex' | 'claude', executable: e.target.value } })}><option value="codex">Codex</option><option value="claude" disabled>Claude · 연결 준비 중</option></select></label><label>모델<input value={draft.agent.model} onChange={e => setDraft({ ...draft, agent: { ...draft.agent, model: e.target.value } })} placeholder="에이전트 기본 모델 사용" /></label></div><label>에이전트 실행 파일<input value={draft.agent.executable} onChange={e => setDraft({ ...draft, agent: { ...draft.agent, executable: e.target.value } })} placeholder="codex 또는 실행 파일 경로" /></label><p className="muted note">설치된 CLI의 로그인 세션을 사용합니다. 대화는 이 앱의 사용자 데이터 폴더에 보관됩니다.</p></div>
    <div className="settings-section"><h2>거래소</h2><label>기본 리그<input value={draft.trade.league} onChange={e => setDraft({ ...draft, trade: { league: e.target.value } })} placeholder="리그 이름" /></label><p className="muted note">채팅에서 조건을 알려주면 POK의 기존 거래 검색 스킬로 검색을 요청할 수 있습니다.</p></div>
    <div className="actions"><button className="primary">설정 저장</button><button type="button" onClick={() => api.openDataFolder().catch(e => setMessage(String(e)))}>사용자 데이터 폴더 열기</button><span role="status">{message}</span></div></form></section>;
}
